[package]
name = "x86_msr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.3.2"
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
raw-cpuid = "10.3.0"