[unstable]
# build-std-features = ["compiler-builtins-mem"]
# build-std = ["core","compiler_builtins","alloc"]
bindeps = true



[target.'cfg(target_os = "none")']
runner = "cargo +nightly run --package loader --target x86_64-unknown-linux-gnu"

[target.x86_64-unknown-none]
rustflags = [
    "-C","relocation-model=static",
    "-C","link-arg=-no-pie",
    "-C","debuginfo=2"
]